on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - run: docker pull alpine
      - run: docker tag alpine ghcr.io/${{ github.repository_owner }}/alpine
      - run: docker login https://ghcr.io -u token -p ${{ secrets.GHCR_TOKEN }}
      - run: docker push ghcr.io/${{ github.repository_owner }}/alpine

  pull:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - run: docker pull ghcr.io/${{ github.repository_owner }}/alpine
