on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}/alpine-test

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: >
          docker build . -t ${{ env.IMAGE }}
          --label org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/
          --label org.opencontainers.image.source=https://github.com/${{ github.repository }}/
          --label org.opencontainers.image.description="I am descriptive"
      - run: docker login https://ghcr.io -u token -p ${{ secrets.GHCR_TOKEN }}
      - run: docker push ${{ env.IMAGE }}

