on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - run: docker pull alpine
      - run: docker tag alpine ghcr.io/${{ github.repository_owner }}/alpine
      - run: docker login https://ghcr.io -u token -p ${{ github.token }}
      - run: docker push alpine ghcr.io/${{ github.repository_owner }}/alpine
