on:
  push:

env:
  IMAGE: ghcr.io/${{ github.repository }}/alpine2

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build -t $IMAGE
      - run: docker login https://ghcr.io -u token -p ${{ secrets.GHCR_TOKEN }}
      - run: docker push $IMAGE

  pull:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - run: docker pull $IMAGE
